### PR TITLE
monex stops refreshing when properties on $data are undefined

### PR DESCRIPTION
**Pull request by nverwer**
When properties on $data are not defined, knockout.js stops refreshing.
Apparently, the eXist-db (6.3.0-SNAPSHOT) JMXServlet does not always defined these properties, so we should catch this condition and provide defaults.

### CODE REVIEW

**Comment by nverwer** [comment]
I found more occurrences of function properties that may sometimes be undefined.
A new commit will be pushed to fix all of them.

**Comment by nverwer** [comment]
> do you mean you tested this against the released version 6.2.0 or the current state of development-6.x.x? 

That's a good point. I mean the dev-6.x.x branch. Monex does work on 6.2.0. So you are right that this could be a regression.  What I see happening is, that the data in the response from `/status` is incomplete, or in a different form than expected. That would point to a problem in the `JMXServlet`, but that has not changed since April 2021.

Now that I think about this again, it could be a Java version problem. We run 6.2.0 on Java 8, and 6.3.0 (development, includes bug fixes that we need) on Java 11. I don't know how the `JMXServlet` serializes JMX data, but the JMX format may have changed between Java 8 and 11.

I should have another look at this, but still the changes in this PR prevent knockout.js from crashing on incomplete data.

**Comment by line-o** [comment]
I agree that we should guard against this in monex.

**Comment by dizzzz** [comment]
I see recently that the JXM content is not shown anymore in Monex. The JMX output is OK when you call the /status URL directory with the token= parameter.

my observation: when accessing from localhost , monex does not work.

**Comment by dizzzz** [comment]
Note: if a newer version of log4j is used (other than the default) then a part of the JMX interface does not work anymore.

in v6.2 I saw a 'non authorized' HTTP code when accessing the /status url

**Comment by nverwer** [comment]
It seems that the tabular structure of the JMX info has changed, at least under some (?) conditions. I have adapted the knockout.js paths to allow for this, and for my 6.3.0 version of eXist this works a lot better.
A new commit has been pushed.

**Review by duncdrum — APPROVED** [review]
@nverwer thanks for your improvements.  I did some manual testing with different combination of exist 6.2 and 6.3 as well as java versions and all looks good.

I m a bit worried that we don't have a test for the crash that you encountered. Can you specify when was a `$data` property null? I'd like to add a test.

**Comment by nverwer** [comment]
@duncdrum It appears that the structure of the properties in `$data` has changed. This is specifically true for tabular data. For example, `$data.sourceKey` was used, but this has now changed to `$data.value.sourceKey`. I think this depends on the Java version, not on the eXist-db version. eXist merely serializes the `javax.management.openmbean.TabularData` object, and the JMXServlet has not changed between 6.2.0 and 6.3.0.
The code changes are such that both `TabularData` serializations work, and if a property is not found, a default value is substituted.

**Comment by dizzzz** [comment]
There were changes with LOG4j and jmx, could that be a factor?

**Comment by nverwer** [comment]
> There were changes with LOG4j and jmx, could that be a factor?

I suspect JMX, but I could not pinpoint a specific (Java) version where this has changed.

**Review by line-o — APPROVED** [review]
@nverwer We discussed this today and came to the conclusion that your changes let Monex gracefully and tells the end user something is wrong when JMX data format has changed. Something that might be opaque to them otherwise.
Thank your for bringing this up.
I will open an issue for the underlying problem so that we don't forget to tackle it.

**Pull request merged**
