### PR TITLE
Update for eXist-db 5.3.0 internal API changes

### PR DESCRIPTION
**Pull request by adamretter**
Closes https://github.com/eXist-db/monex/issues/135

### CODE REVIEW

**Review by windauer — APPROVED** [review]
I tested the PR in the monex remote console and in HSG. Works perfectly fine, thanks Adam!

**Comment by adamretter** [comment]
@windauer @joewiz Okay, then I guess we need a new version of Monex published which is compatible with eXist-db 5.3.0-SNAPSHOT. Would one of you be able to do the honous?

**Comment by windauer** [comment]
@adamretter sure, I will take care of it. I will also replace jquery with a 3.5.x version and try to remove the data view as it was decided by the community. Might take a moment but I plan to get it done today

**Comment by joewiz** [comment]
@adamretter @windauer Many thanks!

**Comment by windauer** [comment]
@adamretter, @joewiz done. I release a 3.0.0 (https://github.com/eXist-db/monex/releases/tag/v3.0.0) cause this PR contained breaking changes and a 2.2.x version will never work on 5.3.0 and a Monex 3.0.0 version not on eXist-db prior 5.3.0-SNAPSHOT.

**Pull request merged**
