### PR TITLE
Get product details from JMX output

### PR DESCRIPTION
**Pull request by adamretter**
Retrieves further product details from JMX rather than hardcoding them.
See https://github.com/eXist-db/exist/pull/2960

### CODE REVIEW

**Comment by joewiz** [comment]
Look good to me, except I had warnings during the build... didn't want to release this version with warnings without clearing it with you first @adamretter?

```
choskimac-ii:monex joe$ mvn clean package
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.exist-db.apps:monex >-----------------------
[INFO] Building Monex 2.0.4
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from exist: http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-core/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.exist-db:exist-core:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-core/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
[WARNING] Failure to transfer org.exist-db:exist-core:5.0.0-SNAPSHOT/maven-metadata.xml from http://repo.exist-db.org/repository/exist-db/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced. Original error: Could not transfer metadata org.exist-db:exist-core:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-core/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
Downloading from exist: http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-parent/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.exist-db:exist-parent:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-parent/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
Downloading from exist: http://repo.exist-db.org/repository/exist-db/org/exist-db/thirdparty/uk/ac/ic/doc/slurp/multilock/multilock/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.exist-db.thirdparty.uk.ac.ic.doc.slurp.multilock:multilock:1.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/thirdparty/uk/ac/ic/doc/slurp/multilock/multilock/1.0-SNAPSHOT/maven-metadata.xml with status code 400
[WARNING] Failure to transfer org.exist-db.thirdparty.uk.ac.ic.doc.slurp.multilock:multilock:1.0-SNAPSHOT/maven-metadata.xml from http://repo.exist-db.org/repository/exist-db/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced. Original error: Could not transfer metadata org.exist-db.thirdparty.uk.ac.ic.doc.slurp.multilock:multilock:1.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/thirdparty/uk/ac/ic/doc/slurp/multilock/multilock/1.0-SNAPSHOT/maven-metadata.xml with status code 400
Downloading from exist: http://repo.exist-db.org/repository/exist-db/org/exist-db/thirdparty/org/deucestm/deuce-annotations/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.exist-db.thirdparty.org.deucestm:deuce-annotations:1.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/thirdparty/org/deucestm/deuce-annotations/1.0-SNAPSHOT/maven-metadata.xml with status code 400
[WARNING] Failure to transfer org.exist-db.thirdparty.org.deucestm:deuce-annotations:1.0-SNAPSHOT/maven-metadata.xml from http://repo.exist-db.org/repository/exist-db/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced. Original error: Could not transfer metadata org.exist-db.thirdparty.org.deucestm:deuce-annotations:1.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/thirdparty/org/deucestm/deuce-annotations/1.0-SNAPSHOT/maven-metadata.xml with status code 400
Downloading from exist: http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-testkit/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.exist-db:exist-testkit:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-testkit/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
[WARNING] Failure to transfer org.exist-db:exist-testkit:5.0.0-SNAPSHOT/maven-metadata.xml from http://repo.exist-db.org/repository/exist-db/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced. Original error: Could not transfer metadata org.exist-db:exist-testkit:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-testkit/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
Downloading from exist: http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-start/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.exist-db:exist-start:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-start/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
[WARNING] Failure to transfer org.exist-db:exist-start:5.0.0-SNAPSHOT/maven-metadata.xml from http://repo.exist-db.org/repository/exist-db/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced. Original error: Could not transfer metadata org.exist-db:exist-start:5.0.0-SNAPSHOT/maven-metadata.xml from/to exist (http://repo.exist-db.org/repository/exist-db/): Failed to transfer file http://repo.exist-db.org/repository/exist-db/org/exist-db/exist-start/5.0.0-SNAPSHOT/maven-metadata.xml with status code 400
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ monex ---
[INFO] Deleting /Users/joe/workspace/monex/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ monex ---
[INFO] 
[INFO] --- buildversion-plugin:1.0.3:set-properties (default) @ monex ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ monex ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/joe/workspace/monex/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ monex ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /Users/joe/workspace/monex/target/classes
[INFO] /Users/joe/workspace/monex/src/main/java/org/exist/console/xquery/JMXToken.java: Some input files use or override a deprecated API.
[INFO] /Users/joe/workspace/monex/src/main/java/org/exist/console/xquery/JMXToken.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/joe/workspace/monex/src/main/java/org/exist/remoteconsole/RemoteConsoleEndpoint.java: /Users/joe/workspace/monex/src/main/java/org/exist/remoteconsole/RemoteConsoleEndpoint.java uses unchecked or unsafe operations.
[INFO] /Users/joe/workspace/monex/src/main/java/org/exist/remoteconsole/RemoteConsoleEndpoint.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ monex ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/joe/workspace/monex/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ monex ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ monex ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ monex ---
[INFO] Building jar: /Users/joe/workspace/monex/target/monex-2.0.4.jar
[INFO] 
[INFO] --- kuberam-expath-plugin:0.6.0:make-xar (create-xar) @ monex ---
[INFO] outputDirectoryPath = /Users/joe/workspace/monex/target
[INFO] descriptorsDirectoryPath: /Users/joe/workspace/monex/target/expath-descriptors
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to /Users/joe/workspace/monex/target/make-xar-tmp
excludesString = .project,.settings/,target/,pom.xml
excludesString = .project,.settings/,target/,pom.xml
[INFO] Resolving artifact org.exist-db.apps:monex:jar:2.0.4.
[INFO] Resolved artifact org.exist-db.apps:monex:jar:2.0.4 to /Users/joe/workspace/monex/target/monex-2.0.4.jar from (reactor)
[INFO] Resolving artifact com.fasterxml.jackson.core:jackson-databind:jar:2.9.9.
[INFO] Resolved artifact com.fasterxml.jackson.core:jackson-databind:jar:2.9.9 to /Users/joe/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.9/jackson-databind-2.9.9.jar from /Users/joe/.m2/repository (enhanced)
[INFO] Resolving artifact com.fasterxml.jackson.core:jackson-annotations:jar:2.9.9.
[INFO] Resolved artifact com.fasterxml.jackson.core:jackson-annotations:jar:2.9.9 to /Users/joe/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.9/jackson-annotations-2.9.9.jar from /Users/joe/.m2/repository (enhanced)
[INFO] Resolving artifact javax.websocket:javax.websocket-api:jar:1.1.
[INFO] Resolved artifact javax.websocket:javax.websocket-api:jar:1.1 to /Users/joe/.m2/repository/javax/websocket/javax.websocket-api/1.1/javax.websocket-api-1.1.jar from /Users/joe/.m2/repository (enhanced)
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to /Users/joe/workspace/monex/target/expath-descriptors
[INFO] Building zip: /Users/joe/workspace/monex/target/monex-2.0.4.xar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.327 s
[INFO] Finished at: 2019-08-30T19:16:08-04:00
[INFO] ------------------------------------------------------------------------
choskimac-ii:monex joe$ 
```

**Comment by joewiz** [comment]
Also, I couldn't find where in pom.xml or elsewhere to put release notes?

**Comment by adamretter** [comment]
@joewiz I can't find the Maven Repository `http://repo.exist-db.org/repository/` defined in the project's `pom.xml`.

Do you perhaps have this specified in your own machines `~/.m2/settings.xml` - if so you should likely remove any entries for it, as it never really worked properly.

**Comment by adamretter** [comment]
@joewiz you could modify the changelog here - https://github.com/eXist-db/monex/blob/master/xar-assembly.xml#L185

**Comment by joewiz** [comment]
@adamretter I don't have a `~/.m2/settings.xml` file. Unsure even how best to release this as it is maven now and there aren't maven-specific release notes in the readme. I have to run now. Sorry!

**Comment by joewiz** [comment]
Thanks for the pointer to the changelog - I had forgotten that! One of these days I should review our core apps for release documentation...

**Comment by joewiz** [comment]
@adamretter I found a couple of references to `http://repo.exist-db.org/repository` in other pom.xmls on my system:

- https://github.com/wolfgangmm/memsort/blob/master/pom.xml#L186-L189
- https://github.com/eXist-db/messaging-replication/blob/develop/pom.xml#L286-L289
- https://github.com/eXist-db/jfreechart/blob/develop/pom.xml#L218-L221

I couldn't figure out how these were polluting monex, so after a `rm -rf ~/.m2`, a `mvn package`, and several minutes of watching maven download things, the build completed. For good measure, I ran `mvn clean package` again, and I saw the same references to http://repo.exist-db.org, so it appears not to be something locally cached, but something fetched by monex? 

Anyway, my local build of your PR works—no errors from any panes, remote console works, so this should be good to go. Monex v2.0.4 will be on its way shortly.

**Comment by adamretter** [comment]
@joewiz okay, so the owners of `memsort`, `messaging-replication`, and `jfreechart` need to update their `pom.xml` files to change repo.

**Comment by joewiz** [comment]
@adamretter Sure, I'll let @wolfgangmm and @dizzzz know to update their respective repositories but my findings show that **monex itself** or things it depends on must have some references to that repository, no? Otherwise, why, after doing `rm -rf ~/.m2` would `mvn package` and then `mvn clean package` on my monex clone produce warnings about that repository? (Sorry, this may just be something specific to my system, or something we can ignore - just mentioning it in case it's something you think is of concern.)

**Pull request merged**
