### PR TITLE
incorporated PR #126 and fixed issue #127

### PR DESCRIPTION
**Pull request by windauer**

### CODE REVIEW

**Review by line-o — COMMENTED** [review]
Code deletion FTW! Thanks for the cleanup.

Since it appears the declared jQuery dependency is not taken into account, I would rather remove it entirely.

**Comment by windauer** [comment]
I don't get this, according to Travis the tests failed for eXist-db latest (5.3.0-SNAPSHOT) but passed for eXist-db release (5.2.0). Either "latest" and "release" is not what I expect it to be or this is simply wrong, because Monex 2.2.0 is not compatible with eXist-db 5.2.0 and can't be installed. And for 5.3.0-SNAPSHOT I checked by hand all functionalities and everything worked perfectly fine. Is it possible that this is an issue with the test setup itself? // cc @adamretter , @duncdrum

**Comment by duncdrum** [comment]
@windauer https://github.com/eXist-db/monex/pull/100#issuecomment-563354631, nope the failing test is consistent with the failing PR you merged . You say it works on your system, but Travis shows it not working on two systems. The ci is working as intended

**Comment by duncdrum** [comment]
@line-o i don’t think using  an undeclared dependency with security loopholes, is a step in the right direction. Instead I’d rather make sure that the declared dependency is actually used in the build. As mentioned before this requires some more work on monex code.

**Comment by line-o** [comment]
@duncdrum having that unused dependency there only hides the fact that jQuery is used in a different version. IMHO much worse.

**Comment by windauer** [comment]
@duncdrum does the eXist-db in travis gets restarted after monex is deployed or is it deployed via autostart? Cause the PR from @adamretter yesterday requires a restart of the database after Monex was deployed. And the expath-package.xml required semver-min="5.3.0-SNAPSHOT" which means its not even possible to install this on a 5.2.0 (latest-release). The travis tests are not failing because of this PR btw but because of the PR by @adamretter yesterday. Since I tested everything by hand I was 100% confident it works fine and overlooked Travis. My fault! I'm a bit helpless on how to proceed now, reverting Adams PR from yesterday can't be the path forward cause it clearly solves the issue that Monex will not work with eXist-db 5.3.0-SNAPSHOT.

**Comment by line-o** [comment]
@windauer our travis CI docker test setup is copying the file in autodeploy, yes. 
see https://github.com/eXist-db/monex/blob/master/.travis.yml#L29
I think it should be possible to start stop and restart the docker instance before testing.
The tests will then likely fail because of the unsupported existdb version that is exist:release (5.2.0) but we should still keep it that way, I believe.

**Comment by line-o** [comment]
I would try this:
```yml
  - docker start exist-ci
  # exist needs time
  - sleep 30
  - docker stop exist-ci
  # exist needs time
  - sleep 30
  - docker start exist-ci
  # exist needs time
  - sleep 30
```

**Comment by duncdrum** [comment]
`:release`  Is working as intended. When the tested monex specifies a semver higher than where `:Release` Is at the test will run against the version of monex that comes out of the box. 

Since a newer build of monex is copied into `:latest` Via autodeploy that’s what the tests run against, you can make sure that it is the first copy of monex to be installed at boot by alphabetic sorting of the xar name in autodeploy. Restarts should not be required, this is how monex ships to users, and if it isn’t working ootb, that needs fixing.

**Comment by duncdrum** [comment]
> @duncdrum having that unused dependency there only hides the fact that jQuery is used in a different version. IMHO much worse.

It is what it is because we needed to convert builds to maven for `5.0.0`. This was discussed at the community call  and here on GitHub, the work that needs to be done is very similar to the documentation apps build, anybody is free to pick it up. 

There are some minor js code adjustments necessary for monex to run with a higher jquery version.

**Comment by windauer** [comment]
closing this PR and will create a new one for removal of data visualizer

**Pull request closed without merging**
