### PR TITLE
Fix new range index field report

### LINKED ISSUE #191: Index for new range field doesn’t show keys [BUG]
**Describe the bug**
I created a range index field for a collection, but Monex doesn’t show any keys for that index. However, a query using the `range` functions confirms that the index has been populated.

**Expected behavior**
I expected to see the keys indexed for the given field.

**To Reproduce**
```Xquery
xquery version "3.1";

  module namespace t="http://example.org/ns/test";
(:  NAMESPACES  :)
  declare namespace range="http://exist-db.org/xquery/range";
  declare namespace test="http://exist-db.org/xquery/xqsuite";
  declare namespace xdb="http://exist-db.org/xquery/xmldb";

(:~
  Check to make sure a named field exists in the new range index.
  
  @author Ash Clark
  2022
 :)
 
(:  VARIABLES  :)
  declare variable $t:pseudojson :=
    <fn:map>
      <fn:string key="id">apple</fn:string>
      <fn:array key="related">
        <fn:string>orange</fn:string>
        <fn:string>pear</fn:string>
      </fn:array>
    </fn:map>;
  
  declare variable $t:xconf :=
    <collection xmlns="http://exist-db.org/collection-config/1.0">
      <index xmlns:fn="http://www.w3.org/2005/xpath-functions"
         xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <range>
          <create qname="fn:string">
            <condition attribute="key" operator="eq" value="id"/>
            <field name="string-id" type="xs:string"/>
          </create>
          <create qname="@key" type="xs:string"/>
        </range>
      </index>
    </collection>;

(:  FUNCTIONS  :)
  
  declare %test:setUp function t:set-up() {
    let $dir := xdb:create-collection('/db', 'sudoJson')
    let $cDir := xdb:create-collection('/db/system/config/db', 'sudoJson')
    let $storeFiles := (
        xdb:store($cDir, 'collection.xconf', $t:xconf),
        xdb:store($dir, 'example.xml', $t:pseudojson)
      )
    return xdb:reindex('/db/sudoJson')
  };
  
  (:declare %test:tearDown function t:tear-down() {
    xdb:remove('/db/sudoJson'), xdb:remove('/db/system/config/db/sudoJson')
  };:)
  
  declare
    %test:assertEquals('apple')
  function t:id-string-field-indexed() {
    collection('/db/sudoJson')/range:index-keys-for-field('string-id', '', 
      function ($i, $d) { $i }, 10)
  };
  
  declare
    %test:assertExists
  function t:query-finds-apple-id() {
    collection('/db/sudoJson')//fn:string[@key eq 'id'][. eq 'apple']
  };
  
  declare
    %test:assertExists
  function t:range-finds-apple-id() {
    collection('/db/sudoJson')/range:field-eq('string-id', 'apple')
  };
  
  declare
    %test:assertEquals(2)
  function t:key-attributes-indexed() {
    let $instances :=
      util:index-keys(collection('/db/sudoJson')//@key, '', function ($i, $d) {
        $d[2]
      }, 10, 'range-index')
    return sum($instances)
  };
```
The test suite above should completely pass, and return something like:

```Xml
<testsuites>
    <testsuite package="http://example.org/ns/test" timestamp="2022-03-25T10:06:51.3-04:00" tests="4" failures="0" errors="0" pending="0" time="PT0.017S">
        <testcase name="id-string-field-indexed" class="t:id-string-field-indexed"/>
        <testcase name="key-attributes-indexed" class="t:key-attributes-indexed"/>
        <testcase name="query-finds-apple-id" class="t:query-finds-apple-id"/>
        <testcase name="range-finds-apple-id" class="t:range-finds-apple-id"/>
    </testsuite>
</testsuites>
```

The tear-down function is commented out, because now you can check what Monex has:

* [Visit the Monex index browsing page for `/db/sudoJson`](http://localhost:8080/exist/apps/monex/index-keys.html?collection=/db/sudoJson).
* Click the link “Node” for the `string-id` indexed item.
* Check the number of keys returned.

There will be 0 results when there should be 1.

**Context**
 - OS: macOS 11.6
 - eXist-db Version: 6.0.1
 - Java Version: openjdk 1.8.0_292
-  App Version: 3.0.4

### PR DESCRIPTION
**Pull request by amclark42**
Fixes #191. Tested on eXist v6.2.0 using previously-created range indexes on elements, attributes, and fields (also, Lucene indexes by node).

This PR ensures that Monex can report on fields in the new range index, and that the report is accurate across a collection.

Monex doesn't have a develop branch. Maintainers, please feel free to let me know if I should adjust this PR at all. Does the app need a changelog entry or a version increase, for instance?

### CODE REVIEW

**Comment by joewiz** [comment]
@amclark42 Thank you for the PR! It is correct in targeting the "master" branch. 

While the CI tests are failing, the issues causing those failures preceded your PR are entirely unrelated to it. I checked out your branch tonight and installed it, and in fact the tests intermittently pass; I hope to get to the bottom of that, separate from this PR.

On the topic of sample data to confirm that the Indexes panel is behaving as expected, I had forgotten that we already have a basis for this: the "indexes-test" subcollection, which can be browsed at http://localhost:8080/exist/apps/monex/collection.html?collection=/db/apps/monex/indexes-test and whose source is https://github.com/eXist-db/monex/blob/master/src/main/xar-resources/indexes-test. You'll see a sample index configurations with a range index for a few cases of elements and attributes with and without namespaces. Would you consider adding some sample data & associated index configurations that, when browsed in Monex's Indexes panel, demonstrates the functionality you added?

**Comment by amclark42** [comment]
@joewiz Absolutely! Thanks for pointing to the test indexes; that'll help a good deal.

Thanks also for investigating the Cypress tests! I tried to get them running locally, but couldn't figure out how to get my environment set up for them. Is there any documentation you can share on how the eXist devs run the tests locally?

**Comment by amclark42** [comment]
I added language to each data file that releases it into the public domain. This way I and others can use the dataset for other purposes. Let me know if this is a problem!

**Comment by amclark42** [comment]
Hi @joewiz! Just curious, what's the status of this PR?

**Comment by joewiz** [comment]
@amclark42 I'm so sorry for the letting so much time pass! Thanks for the reminder! I will review the PR ASAP.

**Comment by joewiz** [comment]
@amclark42 I did a before and after comparison of monex's reports on the test data you added to this PR, and I can confirm that with the old code, monex returned 0 results for the 4 fields, and with the new code, it returns the expected number of results for each. This is really promising!

In my next round of the review, I'll see if I can get the tests running locally and to see if there's something I can add related to the new data & corrected reports.

But before I do, I wanted to comment on the observation in [your Dec. 3 post above](https://github.com/eXist-db/monex/pull/243#issuecomment-1837565604), where you wrote:

> The range function returns one row per term *per document*, not compiled across the corpus... It's worth noting that, if my suspicions are correct, that's fuel for a new bug report on eXist itself and the implemented range function.

As I read your report and [the workaround you added to monex](https://github.com/eXist-db/monex/pull/243/files#diff-14809c785d284f945831ed0466322a20821089e50d52ad595f7a1fb7ce76b4a9R235-R290) to account for this behavior, I agree! 

Would you consider opening an issue to report this bug?

**Comment by joewiz** [comment]
The tests pass locally for me (both via `mvn verify` - which runs the test in a local Docker instance; or one can also run `npm run cypress` after building the package via `mvn package` and installing it on localhost). The tests already passed in CI. The tests mostly just [check](https://github.com/eXist-db/monex/blob/master/src/test/cypress/integration/monex_spec.js#L34-L42) that each of the app's main pages open. I could imagine extending the tests to check that the expected values appear, but I think the tests in the eXist core should really be responsible for checking this behavior. Having your test data in place allows us to confirm that the monex report works. 

So I think this PR is good to go! Thank you *so much* for the fixes! 

(And sorry again for the delay in reviewing it.)

**Review by joewiz — APPROVED** [review]

**Comment by amclark42** [comment]
@joewiz Thank you for your review and encouragement!

> Please consider opening an issue to report this bug, if/when you have the chance. Thank you!

I will try to do so by the end of the year!

**Comment by joewiz** [comment]
@amclark42 Thank you! I think a natural starting point would be the existing tests for the range index fields:

- https://github.com/eXist-db/exist/blob/develop/extensions/indexes/range/src/test/xquery/range/index-keys.xql#L102-L107 (notice the invocation of `range:index-keys-for-field()`)
- https://github.com/eXist-db/exist/blob/develop/extensions/indexes/range/src/test/xquery/range/conditions.xql#L294-L298 (and several other tests after this)
- https://github.com/eXist-db/exist/blob/develop/extensions/indexes/range/src/test/xquery/range/fields.xql (though this doesn't include any instances of `range:index-keys-for-field()`

Notably, these tests only store one test document. Adding a 2nd document (e.g., Act 2) could help illustrate what you observed here.

One other note: My links are to the develop (i.e., 7.0.0-SNAPSHOT) branch, which includes https://github.com/eXist-db/exist/pull/4910 - a PR that altered the format of data returned by eXist's internal performance statistics functions. So depending on which version of eXist you're running, be sure to use the tests drawn from your version of eXist to avoid unexpected errors relating to this. 

I'll be happy to help in any way if you have questions.

**Pull request merged**
